config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :favorites, only: [:create, :destroy]
  end
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  resources :articles
  get 'favorites/index'
  root 'home#index' 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :favorites, dependent: :destroy
    has_many :favoriting_users, through: :favorites, source: :user
    has_many_attached :pictures
    belongs_to :user
    def self.ransackable_attributes(auth_object = nil)
        ["category", "created_at","label", "localisation", "price"]
      end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_articles, through: :favorites, source: :article
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles, dependent: :destroy
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permited_parameters,
                if: :devise_controller?

    protected

    def configure_permited_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [ :phone,:avatar,:lastname,:firstname ])
        devise_parameter_sanitizer.permit(:account_update, keys: [ :phone,:avatar,:lastname,:firstname])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /articles or /articles.json
  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true)
  end

  # GET /articles/1 or /articles/1.json
  def show
    @render_from = "show"
  end



  # GET /articles/new
  def new
    #@article = Article.new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    #@article = Article.new(article_params)
    @article = current_user.articles.build(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @article = current_user.articles.find_by(id: params[:id])
    redirect_to articles_path, notice: "Not Authorized To Edit This Article" if @article.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:label, :price, :description,:condition, :localisation , :category, :user_id, pictures: [])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :authenticate_user!
  

    def index
      @articles = current_user.favorite_articles
      @q = @articles.ransack(params[:q])
      @articles = @q.result(distinct: true)
    
    end


    def create
      @article = Article.find(params[:article_id])
      @favorite = current_user.favorites.build(article: @article)
      if @favorite.save
        redirect_back(fallback_location: root_path)
      else
        redirect_back(fallback_location: root_path, alert: "Unable to add favorite.")
      end
    end
  
    def destroy
      @article = Article.find(params[:article_id])
      @favorite = current_user.favorites.find_by(article_id: @article.id)
      @favorite.destroy
      redirect_back(fallback_location: root_path)
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">


<% if @render_from == "show" %> 

    <p>
    <strong>Label:</strong>
    <%= article.label %>
  </p>

      <p>
    <strong>State:</strong>
    <%= article.condition %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= article.price %>DH
  </p>

  <p>
    <strong>City:</strong>
    <%= article.localisation %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= article.category %>
  </p>

    <p>
    <strong>Published in:</strong>
    <%= article.created_at.to_date %>
  </p>

    <p>
    <strong>User:</strong>
    <%= article.user.lastname %>
    <%= article.user.firstname %>
    <%= phone_to article.user.phone, "Make a Call", country_code: "212" %>
  </p>

  <p>
    <strong>Pictures:</strong>
    <% article.pictures.each do |picture| %>
      <%= image_tag(picture,style:"width:150px;height:150px")%>
    <%end%>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

    <p>
    <strong>User pic:</strong>
    <% if article.user.avatar.attached? %>
    <%= image_tag(article.user.avatar,style:"width:150px;height:150px") %>
    <% else %>
    <%= image_tag("default_profile.jpg",style:"width:150px;height:150px") %>
    <%end%>
  </p>


  <%else%>
<div class="flex flex-row">

<div class="p-2 h-36 w-36 flex justify-center">
      <%= image_tag(article.pictures.first,class:"object-scale-down")%>
  </div>
<div class="p-2 w-60">
  <p>
    <strong class="text-lg"><%= article.label.capitalize %></strong>
    
  </p>
  <div class="ml-1 mt-1">
  <p class="text-sm">
  <strong>City:</strong>
    <%= article.localisation%>
  </p>
      <p class="text-sm">
    <strong>State:</strong>
    <%= article.condition %>
  </p>

  <p class="text-sm">
    <strong>Category:</strong>
    <%= article.category %>
  </p>
  </div>

  </div>
  <div class="border-l-2 p-2 w-40">
  <div class="text-center">
    <div class="mb-2 mt-2 text-green-600">
    <strong><%= article.price %> DH</strong>
  </div>

  <%= phone_to article.user.phone, "Make a Call", country_code: "212", class:"hover:bg-blue-500 hover:text-white text-blue-500 text-sm font-semibold py-1 px-2 rounded-md border-blue-500 border border-2" %>
<div class="mt-6">
    <div class="text-xs text-zinc-600 ">
    <strong>Posted in</strong>
    <%= article.created_at.to_date %>
  </div>

    <div class="text-xs text-zinc-600">
    <strong>Posted by</strong>
    <%= article.user.lastname.capitalize %>
    <%= article.user.firstname.capitalize %>
    
  </div>
  </div>
  </div>
  </div>

  
</div>

<% end %>





  
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :label, style: "display: block" %>
    <%= form.text_field :label , required: true ,pattern: "\\w{3,30}",placeholder: "min 5 character" %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price , required: true %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description , required: true ,pattern: "\\w{15,100}",placeholder: "min 15 character" %>
  </div>

  <div>
    <%= form.label :condition, style: "display: block" %>
    <%= form.select :condition, [ ["New","New"],["Used - Like New","Used - Like New"],["Used - Good","Used - Good"],["Used - Fair","Used - Fair"] ],required: true%>
  </div>

    <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.select :localisation, [  ["Agadir","Agadir"], ["Al Hoceima","Al Hoceima"], ["Azilal","Azilal"], ["Beni Mellal","Beni Mellal"], ["Ben Slimane","Ben Slimane"], ["Boulemane","Boulemane"], ["Casablanca","Casablanca"], ["Chaouen","Chaouen"], ["El Jadida","El Jadida"], ["El Kelaa des Sraghna","El Kelaa des Sraghna"], ["Er Rachidia","Er Rachidia"], ["Essaouira","Essaouira"], ["Fes","Fes"], ["Figuig","Figuig"], ["Guelmim","Guelmim"], ["Ifrane","Ifrane"], ["Kenitra","Kenitra"], ["Khemisset","Khemisset"], ["Khenifra","Khenifra"], ["Khouribga","Khouribga"], ["Laayoune","Laayoune"], ["Larache","Larache"], ["Marrakech","Marrakech"], ["Meknes","Meknes"], ["Nador","Nador"], ["Ouarzazate","Ouarzazate"], ["Oujda","Oujda"], ["Rabat-Sale","Rabat-Sale"], ["Safi","Safi"], ["Settat","Settat"], ["Sidi Kacem","Sidi Kacem"], ["Tangier","Tangier"], ["Tan-Tan","Tan-Tan"], ["Taounate","Taounate"], ["Taroudannt","Taroudannt"], ["Tata","Tata"], ["Taza","Taza"], ["Tetouan","Tetouan"], ["Tiznit","Tiznit"]],required: true%>
  </div>

     <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, [ ["Home & Kitchen","Home & Kitchen"],["Beauty & Personal Care","Beauty & Personal Care"],["Clothing, Shoes & Jewelry","Clothing, Shoes & Jewelry"],["Arts, Crafts & Sewing","Arts, Crafts & Sewing"],["Electronics","Electronics"],["Sports & Outdoors","Sports & Outdoors"],["Health, Household & Baby Care","Health, Household & Baby Care"],["Toys & Games","Toys & Games"],["Cell Phone & Accessories","Cell Phone & Accessories"],["Office Products","Office Products"],["Pet Supplies","Pet Supplies"],["Books","Books"],["Tools & Home Improvement","Tools & Home Improvement"],["Automotive Parts & Accessories","Automotive Parts & Accessories"],["Garden & Outdoor","Garden & Outdoor"],["Handmade","Handmade"],["Collectibles & Fine Art","Collectibles & Fine Art"] ] ,required: true %>
  </div>

  <div>
    <%= form.label :pictures, style: "display: block" %>
    <%= form.file_field :pictures, multiple: true ,required: true%>
  </div>

    <div>
    <%= form.number_field :user_id, id: :article_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="grid grid-cols-5">
<div class="fixed top-14 left-0 w-1/5 h-screen bg-zinc-100 border">

  <h1 class="mt-10 flex justify-center"><div class="font-semibold text-xl text-zinc-700">Search/Sort:</div></h1>

  <%= search_form_for(@q , url: articles_path) do |f| %>
    <div class="flex justify-around p-10">
    <%= sort_link(@q, :price, "Price", default_order: :asc,class:"button-border") %>
    <%= sort_link(@q, :created_at, "Time", default_order: :asc,class:"button-border") %>
    </div>
    <div class="flex flex-col w-60 ml-4">
    <%= f.search_field :label_cont, placeholder: "Search for Articles"  %>
    <br/>
    <%= f.select :localisation_cont, [ ["Select City",""], ["Agadir","Agadir"], ["Al Hoceima","Al Hoceima"], ["Azilal","Azilal"], ["Beni Mellal","Beni Mellal"], ["Ben Slimane","Ben Slimane"], ["Boulemane","Boulemane"], ["Casablanca","Casablanca"], ["Chaouen","Chaouen"], ["El Jadida","El Jadida"], ["El Kelaa des Sraghna","El Kelaa des Sraghna"], ["Er Rachidia","Er Rachidia"], ["Essaouira","Essaouira"], ["Fes","Fes"], ["Figuig","Figuig"], ["Guelmim","Guelmim"], ["Ifrane","Ifrane"], ["Kenitra","Kenitra"], ["Khemisset","Khemisset"], ["Khenifra","Khenifra"], ["Khouribga","Khouribga"], ["Laayoune","Laayoune"], ["Larache","Larache"], ["Marrakech","Marrakech"], ["Meknes","Meknes"], ["Nador","Nador"], ["Ouarzazate","Ouarzazate"], ["Oujda","Oujda"], ["Rabat-Sale","Rabat-Sale"], ["Safi","Safi"], ["Settat","Settat"], ["Sidi Kacem","Sidi Kacem"], ["Tangier","Tangier"], ["Tan-Tan","Tan-Tan"], ["Taounate","Taounate"], ["Taroudannt","Taroudannt"], ["Tata","Tata"], ["Taza","Taza"], ["Tetouan","Tetouan"], ["Tiznit","Tiznit"]]  %>
    <br/>
    <%= f.select :category_cont, [ ["Select Category",""],["Home & Kitchen","Home & Kitchen"],["Beauty & Personal Care","Beauty & Personal Care"],["Clothing, Shoes & Jewelry","Clothing, Shoes & Jewelry"],["Arts, Crafts & Sewing","Arts, Crafts & Sewing"],["Electronics","Electronics"],["Sports & Outdoors","Sports & Outdoors"],["Health, Household & Baby Care","Health, Household & Baby Care"],["Toys & Games","Toys & Games"],["Cell Phone & Accessories","Cell Phone & Accessories"],["Office Products","Office Products"],["Pet Supplies","Pet Supplies"],["Books","Books"],["Tools & Home Improvement","Tools & Home Improvement"],["Automotive Parts & Accessories","Automotive Parts & Accessories"],["Garden & Outdoor","Garden & Outdoor"],["Handmade","Handmade"],["Collectibles & Fine Art","Collectibles & Fine Art"] ] %>
    <br/>
    <%= f.submit "Search" ,class:"button-full"%>
    </div>
  <% end %>
    <div class="mt-16 h-fit text-center border-t-2">
    <div class="py-6  text-zinc-600">Create New Article?</div>
    <%= link_to "New article", new_article_path ,class:"button-border"%>
    </div>
</div>


<div class="col-span-4 col-start-2 ml-4 mr-4 mt-20 mb-8">

<div id="articles" class="grid grid-cols-2 gap-4">
  <% @articles.each do |article| %>
  <%if article.user == current_user%>
  <div class="border-2 relative p-2 shadow">
    <%= render article %>
    <p>
      <%= link_to "Details", article , class:"absolute bottom-3 left-48 bg-blue-500 hover:bg-blue-700 text-sm text-white font-semibold py-1 px-2 rounded-md" %>
    </p>
  </div>
  <%end%>
  <% end %>
</div>
</div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", root_path %>
</div>

app/views/articles/show.html.erb
<%= render @article %>

<div>
  
  <%= link_to "Back to articles", root_path %>
  <%if user_signed_in?%>
    <% if current_user.favorite_articles.include?(@article) %>
      <%= button_to "Unfavorite", article_favorite_path(@article), method: :delete , remote: true %>
    <% else %>
      <%= button_to "Favorite", article_favorites_path(@article), method: :post , remote: true %>
    <% end %>
  <%end%>

  <%if user_signed_in? and @article.user == current_user%>
  <%= link_to "Edit this article", edit_article_path(@article) %> 
  <%= button_to "Destroy this article", @article, method: :delete %>
  <%end%>
</div>

app/views/favorites/index.html.erb
<div class="grid grid-cols-5">
<div class="fixed top-14 left-0 w-1/5 h-screen bg-zinc-100 border">

  <h1 class="mt-10 flex justify-center"><div class="font-semibold text-xl text-zinc-700">Search/Sort:</div></h1>

  <%= search_form_for(@q , url: favorites_index_path) do |f| %>
    <div class="flex justify-around p-10">
    <%= sort_link(@q, :price, "Price", default_order: :asc,class:"button-border") %>
    <%= sort_link(@q, :created_at, "Time", default_order: :asc,class:"button-border") %>
    </div>
    <div class="flex flex-col w-60 ml-4">
    <%= f.search_field :label_cont, placeholder: "Search for Articles"  %>
    <br/>
    <%= f.select :localisation_cont, [ ["Select City",""], ["Agadir","Agadir"], ["Al Hoceima","Al Hoceima"], ["Azilal","Azilal"], ["Beni Mellal","Beni Mellal"], ["Ben Slimane","Ben Slimane"], ["Boulemane","Boulemane"], ["Casablanca","Casablanca"], ["Chaouen","Chaouen"], ["El Jadida","El Jadida"], ["El Kelaa des Sraghna","El Kelaa des Sraghna"], ["Er Rachidia","Er Rachidia"], ["Essaouira","Essaouira"], ["Fes","Fes"], ["Figuig","Figuig"], ["Guelmim","Guelmim"], ["Ifrane","Ifrane"], ["Kenitra","Kenitra"], ["Khemisset","Khemisset"], ["Khenifra","Khenifra"], ["Khouribga","Khouribga"], ["Laayoune","Laayoune"], ["Larache","Larache"], ["Marrakech","Marrakech"], ["Meknes","Meknes"], ["Nador","Nador"], ["Ouarzazate","Ouarzazate"], ["Oujda","Oujda"], ["Rabat-Sale","Rabat-Sale"], ["Safi","Safi"], ["Settat","Settat"], ["Sidi Kacem","Sidi Kacem"], ["Tangier","Tangier"], ["Tan-Tan","Tan-Tan"], ["Taounate","Taounate"], ["Taroudannt","Taroudannt"], ["Tata","Tata"], ["Taza","Taza"], ["Tetouan","Tetouan"], ["Tiznit","Tiznit"]]  %>
    <br/>
    <%= f.select :category_cont, [ ["Select Category",""],["Home & Kitchen","Home & Kitchen"],["Beauty & Personal Care","Beauty & Personal Care"],["Clothing, Shoes & Jewelry","Clothing, Shoes & Jewelry"],["Arts, Crafts & Sewing","Arts, Crafts & Sewing"],["Electronics","Electronics"],["Sports & Outdoors","Sports & Outdoors"],["Health, Household & Baby Care","Health, Household & Baby Care"],["Toys & Games","Toys & Games"],["Cell Phone & Accessories","Cell Phone & Accessories"],["Office Products","Office Products"],["Pet Supplies","Pet Supplies"],["Books","Books"],["Tools & Home Improvement","Tools & Home Improvement"],["Automotive Parts & Accessories","Automotive Parts & Accessories"],["Garden & Outdoor","Garden & Outdoor"],["Handmade","Handmade"],["Collectibles & Fine Art","Collectibles & Fine Art"] ] %>
    <br/>
    <%= f.submit "Search" ,class:"button-full"%>
    </div>
  <% end %>
    <div class="mt-16 h-fit text-center border-t-2">
    <%if user_signed_in?%>
    <div class="py-6  text-zinc-600">Create New Article?</div>
    <%= link_to "New article", new_article_path ,class:"button-border"%>
    <%else%>
    <div class="py-6  text-zinc-600">Don't have an Account?</div>
    <%= link_to "Sign up" , new_user_registration_path ,class:"button-border"%>
    <%end%>
    </div>
</div>


<div class="col-span-4 col-start-2 ml-4 mr-4 mt-20 mb-8">

<div id="articles" class="grid grid-cols-2 gap-4">
  <% @articles.each do |article| %>
  <div class="border-2 relative p-2 shadow">
    <%= render article %>
    <p>
      <%= link_to "Details", article , class:"absolute bottom-3 left-48 bg-blue-500 hover:bg-blue-700 text-sm text-white font-semibold py-1 px-2 rounded-md" %>
    </p>
  </div>
  <% end %>
</div>
</div>
</div>

app/views/home/_header.html.erb
<nav class=" fixed top-0 left-0 right-0 z-10 w-full flex justify-between py-3 px-5 bg-zinc-100 border">
        <div class="">
        <%= link_to "E-Market" , root_path ,class:"text-xl font-semibold"%>
        </div>
        <div class="">
        <% if user_signed_in? %>
        <%= link_to "My Favorites", favorites_index_path ,class:" button-full" %>
        <%= link_to "My Articles", articles_path ,class:"button-full" %>
        <%= link_to "Edit Account", edit_user_registration_path ,class:"button-full" %>
        <%= link_to "Sign out", destroy_user_session_path, class:"button-full" %>
        <%else%>
        <%= link_to "Sign in", new_user_session_path ,class:"button-full" %>
        <%end%>
        </div>
        
</nav>

app/views/home/index.html.erb
<div class="grid grid-cols-5">
<div class="fixed top-14 left-0 w-1/5 h-screen bg-zinc-100 border">

  <h1 class="mt-10 flex justify-center"><div class="font-semibold text-xl text-zinc-700">Search/Sort:</div></h1>

  <%= search_form_for(@q , url: root_path) do |f| %>
    <div class="flex justify-around p-10">
    <%= sort_link(@q, :price, "Price", default_order: :asc,class:"button-border") %>
    <%= sort_link(@q, :created_at, "Time", default_order: :asc,class:"button-border") %>
    </div>
    <div class="flex flex-col w-60 ml-4">
    <%= f.search_field :label_cont, placeholder: "Search for Articles"  %>
    <br/>
    <%= f.select :localisation_cont, [ ["Select City",""], ["Agadir","Agadir"], ["Al Hoceima","Al Hoceima"], ["Azilal","Azilal"], ["Beni Mellal","Beni Mellal"], ["Ben Slimane","Ben Slimane"], ["Boulemane","Boulemane"], ["Casablanca","Casablanca"], ["Chaouen","Chaouen"], ["El Jadida","El Jadida"], ["El Kelaa des Sraghna","El Kelaa des Sraghna"], ["Er Rachidia","Er Rachidia"], ["Essaouira","Essaouira"], ["Fes","Fes"], ["Figuig","Figuig"], ["Guelmim","Guelmim"], ["Ifrane","Ifrane"], ["Kenitra","Kenitra"], ["Khemisset","Khemisset"], ["Khenifra","Khenifra"], ["Khouribga","Khouribga"], ["Laayoune","Laayoune"], ["Larache","Larache"], ["Marrakech","Marrakech"], ["Meknes","Meknes"], ["Nador","Nador"], ["Ouarzazate","Ouarzazate"], ["Oujda","Oujda"], ["Rabat-Sale","Rabat-Sale"], ["Safi","Safi"], ["Settat","Settat"], ["Sidi Kacem","Sidi Kacem"], ["Tangier","Tangier"], ["Tan-Tan","Tan-Tan"], ["Taounate","Taounate"], ["Taroudannt","Taroudannt"], ["Tata","Tata"], ["Taza","Taza"], ["Tetouan","Tetouan"], ["Tiznit","Tiznit"]]  %>
    <br/>
    <%= f.select :category_cont, [ ["Select Category",""],["Home & Kitchen","Home & Kitchen"],["Beauty & Personal Care","Beauty & Personal Care"],["Clothing, Shoes & Jewelry","Clothing, Shoes & Jewelry"],["Arts, Crafts & Sewing","Arts, Crafts & Sewing"],["Electronics","Electronics"],["Sports & Outdoors","Sports & Outdoors"],["Health, Household & Baby Care","Health, Household & Baby Care"],["Toys & Games","Toys & Games"],["Cell Phone & Accessories","Cell Phone & Accessories"],["Office Products","Office Products"],["Pet Supplies","Pet Supplies"],["Books","Books"],["Tools & Home Improvement","Tools & Home Improvement"],["Automotive Parts & Accessories","Automotive Parts & Accessories"],["Garden & Outdoor","Garden & Outdoor"],["Handmade","Handmade"],["Collectibles & Fine Art","Collectibles & Fine Art"] ] %>
    <br/>
    <%= f.submit "Search" ,class:"button-full"%>
    </div>
  <% end %>
    <div class="mt-16 h-fit text-center border-t-2">
    <%if user_signed_in?%>
    <div class="py-6  text-zinc-600">Create New Article?</div>
    <%= link_to "New article", new_article_path ,class:"button-border"%>
    <%else%>
    <div class="py-6  text-zinc-600">Don't have an Account?</div>
    <%= link_to "Sign up" , new_user_registration_path ,class:"button-border"%>
    <%end%>
    </div>
</div>


<div class="col-span-4 col-start-2 ml-4 mr-4 mt-20 mb-8">

<div id="articles" class="grid grid-cols-2 gap-4">
  <% @articles.each do |article| %>
  <div class="border-2 relative p-2 shadow">
    <%= render article %>
    <p>
      <%= link_to "Details", article , class:"absolute bottom-3 left-48 bg-blue-500 hover:bg-blue-700 text-sm text-white font-semibold py-1 px-2 rounded-md" %>
    </p>
  </div>
  <% end %>
</div>
</div>
</div>

app/views/layouts/_alerts.html.erb
<div class=" w-fit h-fit px-4 py-3 flex items-center text-white border-0 rounded relative bg-yellow-500">
  <span class="inline-block align-middle mr-8">
    <b class="capitalize"><%= notice %></b>
  </span>
  <button class="absolute bg-transparent text-2xl font-semibold leading-none right-0 mr-4 outline-none focus:outline-none" onclick="closeAlert(event)">
    <span>×</span>
  </button>
</div>
<script>
  function closeAlert(event){
    let element = event.target;
    while(element.nodeName !== "BUTTON"){
      element = element.parentNode;
    }
    element.parentNode.parentNode.removeChild(element.parentNode);
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-Market</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      </head>

  <body class="">
    <%= render 'home/header'%>
    <% if notice %>
    <div class="z-20 fixed w-full flex justify-center">
      <%= render 'layouts/alerts'%>
    </div>
    <%end%>
    <%= yield %>
    </div>
  
    </body>
</html>